name: make lint, test and deploy
on:
    - push
    - pull_request
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v4
            - name: install node
              uses: actions/setup-node@v4
            - run: npm install
    install:
        runs-on: ubuntu-latest
        steps:
        #   - run: cd ../
          - run: pwd
          - run: ls -la
          - run: cd ""../""
          - run: pwd
          - run: ls -la
          - name: install dependencies
            run: npm install
        needs: setup
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: make lint    
              run: npx eslint .
        needs: install

    test:
        runs-on: ubuntu-latest
        steps:
            - name: make test
              run: npm test
        needs: install
