name: make lint, test and deploy
on:
  - push
  - pull_request
jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: install node
        uses: actions/setup-node@v4
      - run: npm install

      - name: install dependencies
        run: npm install

      - name: make lint    
        run: npx eslint .

      - name: make test
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test_and_lint
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          rm: true
          source: "./src/index.html"
          target: "/home/admin/index.html"

          # docker run --name nginx -p 80:80 -v ~/index.html:/usr/share/nginx/html/index.html -d nginx