name: make lint, test and deploy
on:
  - push
  - pull_request
jobs:
  # test_and_lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v4

  #     - name: install node
  #       uses: actions/setup-node@v4
  #     - run: npm install

  #     - name: install dependencies
  #       run: npm install

  #     - name: make lint    
  #       run: npx eslint .

  #     - name: make test
  #       run: npm test


  # Для того, чтобы деплой заработал мне нужно установить SSH-соединение вм гитхаба и сервера,
  # проброс статического контента уже настроен, нужно только запустить контйнер с nginx 
  deploy:
    runs-on: ubuntu-latest
    # needs: test_and_lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # Install ssh key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.SSH }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
          
      - name: Generate auth hosts
        run: ssh-keyscan -H 90.156.216.32 >> ~/.ssh/known_hosts

      # - name: Install SSH Key
      #   run: touch ~/.ssh/id_rsa && echo ${{ secrets.SSH }} >> ~/.ssh/id_rsa
        
      # - name: Generate auth hosts
      #   run: touch ~/.ssh/known_hosts && echo ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts


      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_RNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          rm: true
          source: "./src/index.js"
          target: "/home/admin/index.js"

          # docker run --name nginx -p 80:80 -v ~/index.html:/usr/share/nginx/html/index.html -d nginx