name: make lint, test and deploy
on:
  - push
  - pull_request
jobs:
  # test_and_lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out the repo
  #       uses: actions/checkout@v4

  #     - name: install node
  #       uses: actions/setup-node@v4
  #     - run: npm install

  #     - name: install dependencies
  #       run: npm install

  #     - name: make lint    
  #       run: npx eslint .

  #     - name: make test
  #       run: npm test

  deploy:
    runs-on: ubuntu-latest
    # needs: test_and_lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # Install ssh key
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with:
          key: "${{ secrets.SSH }}"
          known_hosts: "just-a-placeholder-so-we-dont-get-errors"
        
      - name: Generate auth hosts
        run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts


      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_RNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          rm: true
          source: "./src/index.js"
          target: "/home/admin/index.js"

          # docker run --name nginx -p 80:80 -v ~/index.html:/usr/share/nginx/html/index.html -d nginx